define(["require", "exports", "../components/highlight_token"], function (require, exports, highlight_token) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.components = {
        highlight_token: highlight_token,
    };
    var text = [{ "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "v", "word": "\u662f" }, { "flag": "v", "word": "\u7ad9" }, {
            "flag": "uz", "word": "\u7740"
        }, { "flag": "v", "word": "\u559d\u9152" }, { "flag": "c", "word": "\u800c" }, { "flag": "v", "word": "\u7a7f" }, { "flag": "n", "word": "\u957f\u886b" }, { "flag": "uj", "word": "\u7684" }, { "flag": "b", "word": "\u552f\u4e00" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u4eba" }, { "flag": "x", "word": "\u3002" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "n", "word": "\u8eab\u6750" }, { "flag": "zg", "word": "\u5f88" }, { "flag": "a", "word": "\u9ad8\u5927" }, { "flag": "x", "word": "\uff1b" }, { "flag": "n", "word": "\u9752\u767d" }, { "flag": "n", "word": "\u8138\u8272" }, { "flag": "x", "word": "\uff0c" }, { "flag": "n", "word": "\u76b1\u7eb9" }, { "flag": "f", "word": "\u95f4" }, { "flag": "d", "word": "\u65f6\u5e38" }, { "flag": "v", "word": "\u5939" }, { "flag": "q", "word": "\u4e9b" }, { "flag": "n", "word": "\u4f24\u75d5" }, { "flag": "x", "word": "\uff1b" }, { "flag": "m", "word": "\u4e00\u90e8" }, { "flag": "z", "word": "\u4e71\u84ec\u84ec" }, { "flag": "uj", "word": "\u7684" }, { "flag": "nr", "word": "\u82b1\u767d" }, { "flag": "uj", "word": "\u7684" }, { "flag": "nr", "word": "\u80e1\u5b50" }, { "flag": "x", "word": "\u3002" }, { "flag": "v", "word": "\u7a7f" }, { "flag": "uj", "word": "\u7684" }, { "flag": "c", "word": "\u867d\u7136" }, { "flag": "v", "word": "\u662f" }, { "flag": "n", "word": "\u957f\u886b" }, { "flag": "x", "word": "\uff0c" }, { "flag": "c", "word": "\u53ef\u662f" }, { "flag": "d", "word": "\u53c8" }, { "flag": "a", "word": "\u810f" }, { "flag": "d", "word": "\u53c8" }, { "flag": "v", "word": "\u7834" }, { "flag": "x", "word": "\uff0c" }, { "flag": "d", "word": "\u4f3c\u4e4e" }, { "flag": "m", "word": "\u5341\u591a\u5e74" }, { "flag": "v", "word": "\u6ca1\u6709" }, { "flag": "v", "word": "\u8865" }, { "flag": "x", "word": "\uff0c" }, { "flag": "d", "word": "\u4e5f" }, { "flag": "v", "word": "\u6ca1\u6709" }, {
            "flag": "v", "word": "\u6d17"
        }, { "flag": "x", "word": "\u3002" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "p", "word": "\u5bf9" }, { "flag": "n", "word": "\u4eba" }, { "flag": "v", "word": "\u8bf4\u8bdd" }, { "flag": "x", "word": "\uff0c" }, { "flag": "c", "word": "\u603b\u662f" }, { "flag": "ns", "word": "\u6ee1\u53e3" }, { "flag": "i", "word": "\u4e4b\u4e4e\u8005\u4e5f" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u53eb" }, { "flag": "n", "word": "\u4eba" }, { "flag": "l", "word": "\u534a\u61c2\u4e0d\u61c2" }, { "flag": "uj", "word": "\u7684" }, { "flag": "x", "word": "\u3002" }, { "flag": "c", "word": "\u56e0\u4e3a" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "v", "word": "\u59d3" }, { "flag": "nr", "word": "\u5b54" }, { "flag": "x", "word": "\uff0c" }, { "flag": "r", "word": "\u522b\u4eba" }, { "flag": "d", "word": "\u4fbf" }, { "flag": "p", "word": "\u4ece" }, { "flag": "v", "word": "\u63cf\u7ea2" }, { "flag": "n", "word": "\u7eb8" }, { "flag": "f", "word": "\u4e0a" }, { "flag": "uj", "word": "\u7684" }, { "flag": "x", "word": "\u201c" }, { "flag": "f", "word": "\u4e0a" }, { "flag": "n", "word": "\u5927\u4eba" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "x", "word": "\u201d" }, { "flag": "r", "word": "\u8fd9" }, { "flag": "l", "word": "\u534a\u61c2\u4e0d\u61c2" }, { "flag": "u", "word": "\u7684\u8bdd" }, { "flag": "f", "word": "\u91cc" }, { "flag": "x", "word": "\uff0c" }, { "flag": "p", "word": "\u66ff" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "v", "word": "\u53d6\u4e0b" }, { "flag": "m", "word": "\u4e00\u4e2a" }, { "flag": "n", "word": "\u7ef0\u53f7" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u53eb\u4f5c" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "x", "word": "\u3002" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "m", "word": "\u4e00" }, { "flag": "v", "word": "\u5230" }, { "flag": "n", "word": "\u5e97" }, { "flag": "x", "word": "\uff0c" }, { "flag": "b", "word": "\u6240\u6709" }, { "flag": "v", "word": "\u559d\u9152" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u4eba" }, { "flag": "d", "word": "\u4fbf" }, { "flag": "d", "word": "\u90fd" }, { "flag": "v", "word": "\u770b\u7740" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "v", "word": "\u7b11" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u6709" }, { "flag": "uj", "word": "\u7684" }, { "flag": "v", "word": "\u53eb\u9053" }, { "flag": "x", "word": "\uff0c" }, { "flag": "x", "word": "\u201c" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "x", "word": "\uff0c" }, { "flag": "r", "word": "\u4f60" }, { "flag": "s", "word": "\u8138\u4e0a" }, {
            "flag": "d",
            "word": "\u53c8"
        }, { "flag": "v", "word": "\u6dfb" }, { "flag": "f", "word": "\u4e0a" }, { "flag": "a", "word": "\u65b0" }, { "flag": "n", "word": "\u4f24\u75a4" }, { "flag": "ul", "word": "\u4e86" }, { "flag": "x", "word": "\uff01" }, { "flag": "x", "word": "\u201d" }, { "flag": "r", "word": "\u4ed6" }, { "flag": "d", "word": "\u4e0d" }, { "flag": "v", "word": "\u56de\u7b54" }, { "flag": "x", "word": "\uff0c" }, { "flag": "p", "word": "\u5bf9" }, { "flag": "s", "word": "\u67dc\u91cc" }, { "flag": "v", "word": "\u8bf4" }, { "flag": "x", "word": "\uff0c" }, { "flag": "x", "word": "\u201c" }, { "flag": "nr", "word": "\u6e29" }, { "flag": "m", "word": "\u4e24\u7897" }, { "flag": "n", "word": "\u9152" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u8981" }, { "flag": "n", "word": "\u4e00\u789f" }, { "flag": "n", "word": "\u8334\u9999\u8c46" }, { "flag": "x", "word": "\u3002" }, { "flag": "x", "word": "\u201d" }, { "flag": "d", "word": "\u4fbf" }, { "flag": "v", "word": "\u6392\u51fa" }, { "flag": "nz", "word": "\u4e5d\u6587" }, { "flag": "n", "word": "\u5927\u94b1" }, { "flag": "x", "word": "\u3002" }, { "flag": "r", "word": "\u4ed6\u4eec" }, { "flag": "d", "word": "\u53c8" }, { "flag": "d", "word": "\u6545\u610f" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u9ad8\u58f0" }, { "flag": "v", "word": "\u56b7" }, { "flag": "q", "word": "\u9053" }, { "flag": "x", "word": "\uff0c" }, { "flag": "x", "word": "\u201c" }, { "flag": "r", "word": "\u4f60" }, { "flag": "d", "word": "\u4e00\u5b9a" }, { "flag": "d", "word": "\u53c8" }, { "flag": "v", "word": "\u5077" }, { "flag": "ul", "word": "\u4e86" }, { "flag": "n", "word": "\u4eba\u5bb6" }, { "flag": "uj", "word": "\u7684" }, { "flag": "ns", "word": "\u4e1c\u897f" }, { "flag": "ul", "word": "\u4e86" }, { "flag": "x", "word": "\uff01" }, { "flag": "x", "word": "\u201d" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "n", "word": "\u7741\u5927\u773c\u775b" }, { "flag": "v", "word": "\u8bf4" }, { "flag": "x", "word": "\uff0c" }, { "flag": "x", "word": "\u201c" }, { "flag": "r", "word": "\u4f60" }, { "flag": "r", "word": "\u600e\u4e48" }, { "flag": "r", "word": "\u8fd9\u6837" }, { "flag": "n", "word": "\u51ed\u7a7a" }, { "flag": "n", "word": "\u6c61\u4eba" }, { "flag": "a", "word": "\u6e05\u767d" }, { "flag": "x", "word": "\u2026" }, { "flag": "x", "word": "\u2026" }, { "flag": "x", "word": "\u201d" }, {
            "flag": "x", "word": "\u201c"
        }, { "flag": "r", "word": "\u4ec0\u4e48" }, { "flag": "a", "word": "\u6e05\u767d" }, { "flag": "x", "word": "\uff1f" },
        { "flag": "r", "word": "\u6211" }, { "flag": "t", "word": "\u524d\u5929" }, { "flag": "d", "word": "\u4eb2\u773c" }, { "flag": "v", "word": "\u89c1" }, { "flag": "r", "word": "\u4f60" }, { "flag": "v", "word": "\u5077" }, { "flag": "ul", "word": "\u4e86" },
        { "flag": "r", "word": "\u4f55\u5bb6" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u4e66" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u540a" }, { "flag": "uz", "word": "\u7740" }, { "flag": "v", "word": "\u6253" }, { "flag": "x", "word": "\u3002" }, { "flag": "x", "word": "\u201d" }, { "flag": "nr", "word": "\u5b54\u4e59\u5df1" }, { "flag": "d", "word": "\u4fbf" }, { "flag": "n", "word": "\u6da8\u7ea2\u4e86\u8138" }, { "flag": "x", "word": "\uff0c" }, { "flag": "n", "word": "\u989d" }, { "flag": "f", "word": "\u4e0a" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u9752\u7b4b" }, { "flag": "n", "word": "\u6761\u6761" }, { "flag": "v", "word": "\u7efd\u51fa" }, { "flag": "x", "word": "\uff0c" }, {
            "flag": "v",
            "word": "\u4e89\u8fa9"
        }, { "flag": "q", "word": "\u9053" }, { "flag": "x", "word": "\uff0c" }, { "flag": "x", "word": "\u201c" }, { "flag": "vg", "word": "\u7a83" }, { "flag": "n", "word": "\u4e66" }, { "flag": "v", "word": "\u4e0d\u80fd" }, {
            "flag": "v",
            "word": "\u7b97"
        }, { "flag": "v", "word": "\u5077" }, { "flag": "x", "word": "\u2026" }, { "flag": "x", "word": "\u2026" }, { "flag": "vg", "word": "\u7a83" }, { "flag": "n", "word": "\u4e66" }, { "flag": "x", "word": "\uff01" }, { "flag": "x", "word": "\u2026" }, { "flag": "x", "word": "\u2026" }, { "flag": "n", "word": "\u8bfb\u4e66\u4eba" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u4e8b" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u80fd\u7b97" }, { "flag": "d", "word": "\u5077\u4e48" }, { "flag": "x", "word": "\uff1f" }, { "flag": "x", "word": "\u201d" }, { "flag": "v", "word": "\u63a5\u8fde" }, { "flag": "v", "word": "\u4fbf\u662f" }, { "flag": "a", "word": "\u96be\u61c2" }, { "flag": "u", "word": "\u7684\u8bdd" }, { "flag": "x", "word": "\uff0c" }, { "flag": "r", "word": "\u4ec0\u4e48" }, { "flag": "x", "word": "\u201c" }, { "flag": "l", "word": "\u541b\u5b50\u56fa\u7a77" }, { "flag": "x", "word": "\u201d" }, { "flag": "x", "word": "\uff0c" }, { "flag": "r", "word": "\u4ec0\u4e48" }, { "flag": "x", "word": "\u201c" }, { "flag": "k", "word": "\u8005" }, { "flag": "y", "word": "\u4e4e" }, {
            "flag": "x", "word": "\u201d"
        }, { "flag": "r", "word": "\u4e4b\u7c7b" }, { "flag": "x", "word": "\uff0c" }, { "flag": "v", "word": "\u5f15\u5f97" }, { "flag": "n", "word": "\u4f17\u4eba" }, { "flag": "d", "word": "\u90fd" }, { "flag": "v", "word": "\u54c4\u7b11" }, { "flag": "v", "word": "\u8d77\u6765" }, { "flag": "x", "word": "\uff1a" }, { "flag": "n", "word": "\u5e97" }, { "flag": "s", "word": "\u5185\u5916" }, { "flag": "a", "word": "\u5145\u6ee1" }, { "flag": "ul", "word": "\u4e86" }, { "flag": "d", "word": "\u5feb\u6d3b" }, { "flag": "uj", "word": "\u7684" }, { "flag": "n", "word": "\u7a7a\u6c14" }, { "flag": "x", "word": "\u3002" }];
    var vm = {
        text: text
    };
    exports.default = vm;
});
